import { v4 as uuidv4 } from "uuid";

export const membersData = [
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Samir Valiyev",
		profession: "Front End Developer",
		github: "https://github.com/samirvaliyev",
		linkedin: "https://www.linkedin.com/in/samir-valiyev-a0b40832/",
		twitter: "https://twitter.com/samirvaliyev89",
		facebook: "https://www.facebook.com/samirvaliyev89/",
	},
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Hacımurad Əzizov",
		profession: "Front End Developer",
		github: "https://github.com/Hacimurad",
		linkedin: "#",
		twitter: "#",
		facebook: "https://www.facebook.com/HacimuradAzizov",
	},
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Fidan Nağıyeva",
		profession: "Front End Developer",
		github: "https://github.com/fynaghk",
		linkedin: "#",
		twitter: "#",
		facebook: "#",
	},
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Turan Balayev",
		profession: "Front End Developer",
		github: "https://github.com/turanbalayev",
		linkedin: "#",
		twitter: "#",
		facebook: "https://www.facebook.com/turan.balayev.77/",
	},
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Cavid Əliyev",
		profession: "Front End Developer",
		github: "https://github.com/cavid-aliyev",
		linkedin: "#",
		twitter: "#",
		facebook: "#",
	},
	{
		id: uuidv4(),
		image: "https://st.depositphotos.com/2101611/3925/v/600/depositphotos_39258143-stock-illustration-businessman-avatar-profile-picture.jpg",
		name: "Elvin Yeka",
		profession: "Front End Developer",
		github: "https://github.com/elvinyeka",
		linkedin: "#",
		twitter: "#",
		facebook: "https://www.facebook.com/profile.php?id=100009894554730/",
	},
];
